[package]
name = "data"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
serde.workspace = true
iced_core.workspace = true
chrono.workspace = true
log.workspace = true
thiserror.workspace = true
regex.workspace = true
palette.workspace = true
enum-map.workspace = true
rustc-hash.workspace = true
dirs-next = "2.0.0"
rodio = { version = "0.20.1", default-features = false, features = [ "wav" ]}
open = "5.3.2"
anyhow = "1.0"
bytes.workspace = true

exchange = { version = "0.1.0", path = "../exchange" }
storage = { path = "../storage" }
arrow = "57.0.0"
parquet = { version = "57.0.0", features = ["arrow"] }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-native-roots"] }
futures-util = "0.3"

# GPGPU compute dependencies
bytemuck = { version = "1.12", features = [ "derive" ] }
futures-intrusive = "0.5.0"
iced = { version = "0.14.0-dev", default-features = false, features = ["wgpu"] }
wgpu = "0.19" # Adding direct wgpu dependency back

[patch.crates-io]
iced = { git = "https://github.com/iced-rs/iced", rev = "c538311ee0ed9026a7d6fabc00971b306a56fe61" }
iced_futures = { git = "https://github.com/iced-rs/iced", rev = "c538311ee0ed9026a7d6fabc00971b306a56fe61" }
iced_core = { git = "https://github.com/iced-rs/iced", rev = "c538311ee0ed9026a7d6fabc00971b306a56fe61"}
